config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create]
  resources :notifications, only: :index
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_like, only: [:create, :destroy]

  def create
    like = current_user.likes.new(post_id: @post.id)
    like.save
    @post.create_notification_by(current_user)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id).destroy
  end

  private

  def set_like
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(post) %>
    <%= link_to(post_likes_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
      <div class="flex-likes">
        <div class= likes-icon>
          <i class="bi bi-suit-heart-fill"></i>
        </div>
        <div class="likes-count">
          <%= post.likes.count %>
        </div>
      </div>
    <% end %>
<% else %>
    <%= link_to(post_likes_path(post), method: :post, remote: true, id: :"like-button-#{post.id}") do %>
      <div class="flex-likes">
        <div class= likes-icon>
          <i class="bi bi-suit-heart"></i>
        </div>
        <div class="likes-count">
          <%= post.likes.count %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>