config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create]
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, through: :likes
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :reads, dependent: :destroy

  mount_uploader :image, ImageUploader

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  with_options presence: true do
    validates :nickname
    validates :password_confirmation, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'には英字と数字の両方を含めて設定してください' },
                                      if: :password_required?
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'には全角文字を使用してください' }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'には全角文字を使用してください' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'には全角カナを使用してください' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'には全角カナ文字を使用してください' }
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def active_for_authentication?
    super && !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(_resource)
    user_path(@user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :set_user, only: [:show, :following, :followers]

  def show
    @post = Post.where(user_id: current_user.id).includes(:user).order('created_at DESC')
    @posts = @user.posts.page(params[:page]).reverse_order
    @following_users = @user.following
    @follower_users = @user.followers
  end

  def following
    @users = @user.following
    render 'follows'
  end

  def followers
    @users = @user.followers
    render 'followers'
  end

  def create
    @user = User.find(params[:following_id])
    current_user.follow(@user)
    @user.create_notification_follow!(current_user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォロー", class: "form__btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "form__btn" %>
<% end %>

app/views/users/followers.html.erb
<% breadcrumb :followers_user, @user %>
<div class="registration-main">
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        フォロワー
      </h1>
    </div>
    <div>
      <% @users.each do |user| %>
        <%= link_to user_path(user) do %>
        <div class="follow-header">
          <div class="user-image">
            <% if user.image? %>
              <%= image_tag user.image.url %>
            <% else %>
              <%= image_tag("/images/no-image.png") %>
            <% end %>
          </div>
          <div class="follow-right">
            <div class="user-nickname">
            <%= user.nickname %>
            </div>
            <div class="user-introduce">
            <%= user.introduce %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<% breadcrumb :follows_user, @user %>
<div class="registration-main">
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        フォロー
      </h1>
    </div>
    <div>
      <% @users.each do |user| %>
        <%= link_to user_path(user) do %>
        <div class="follow-header">
          <div class="user-image">
            <% if user.image? %>
              <%= image_tag user.image.url %>
            <% else %>
              <%= image_tag("/images/no-image.png") %>
            <% end %>
          </div>
          <div class="follow-right">
            <div class="user-nickname">
              <%= "#{user.nickname}先生" %>
            </div>
            <div class="user-introduce">
              <%= user.introduce %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% breadcrumb :user_show, @user %>
<div class="user_main">
  <div class="inner">
    <div class="user__wrapper">
      <div class="flex-row">
        <div class="h2">
          <h2 class="page-heading-show">
            <%= "#{@user.nickname}先生のプロフィール"%>
          </h2>
        </div>
      </div>

      <div class="user-profile">
        <div class="profile-left">
          <div class="profile-card">
            <div class="card-header">
              <%= "#{@user.nickname}先生" %>
              <span><%= "(#{@user.age}代" %> <%= "#{@user.sex})" %></span>
            </div>
            <div class="card-image">
              <% if @user.image? %>
                <%= image_tag @user.image.url %>
              <% else %>
                <%= image_tag("/images/no-image.png") %>
              <% end %>
            </div>
            <div class="card-footer">
              <div id="user-follows">
                <div class="follower">
                  <%= link_to followers_user_path(@user.id) do %>
                  <div class="h5" style="color: black;">フォロワー<%= @user.followers.count %>人</div>
                  <% end %>
                </div>
                <div class="follow">
                  <%= link_to following_user_path(@user.id) do %>
                    <h5 style="color: black;">フォロー<%= @user.following.count %>人</h5>
                  <% end %>
                </div>
              <div class="card-footer-flex"> 
                <div class="follow-btn">
                  <%= render "follow_form" %>
                </div> 
                <div class="chat_btn">
                  <% if user_signed_in? && current_user.id != @user.id %>
                    <%= link_to "チャット", chat_path(@user.id), class: :form__btn %>
                  <% end %>
                </div>
              </div>
              <div class="card-footer-flex"> 
                <div class="edit-btn">
                  <% if user_signed_in? && @user.id == current_user.id %>
                    <%= link_to "編集する", edit_user_registration_path(@user), class: :form__btn %>
                  <% end %>
                </div>
                <div class="withdrawal-btn">
                  <% if user_signed_in? && current_user.id == @user.id %>
                    <%= link_to '退会', user_registration_path, class: :form__btn, method: :delete, data: { confirm: "アカウントを削除してもよろしいですか？" } %>
                  <% end %>
                </div>
              </div>
            </div>  
          </div>
        </div> 
        </div>
        <div class="profile-right">
          <table class="table">
            <tbody>
              <tr>
                <th class="table__col1", style="border-radius: 5px 0 0 0;">学校名</th>
                <td class="table__col2", style="border-radius: 0 5px 0 0;"><%= @user.school %></td>
              </tr>
              <tr>
                <th class="table__col1">担当教科</th>
                <td class="table__col2"><%= @user.subject %></td>
              </tr>
              <tr>
                <th class="table__col1">部活動</th>
                <td class="table__col2"><%= @user.club %></td>
              </tr>
              <tr>
                <th class="table__col3", style="border-radius: 0 0 0 5px;">自己紹介</th>
                <td class="table__col4", style="border-radius: 0 0 5px 0;"><%= @user.introduce %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <h2 class="page-heading">
        <%= "#{@user.nickname}先生の投稿"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'posts/post', collection: @post %>
      </div>
      <h2 class="page-heading">
        <%= "#{@user.nickname}先生がいいねした投稿"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'posts/post', collection: @user.posts %>
      </div>
    </div>
  </div>
</div>