config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create]
  resources :notifications, only: :index
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="copyright">Copyright © KYOYU All rights reserved.</p>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to image_tag("logo.png", class: :logo), root_path %>
      </div>

      <div class="search">
        <%= form_with url: posts_path, method: :get, local: true do |f| %>
          <%= f.text_field :search, class:"input-search", id:"post_form_tag_name", maxlength:"40" %>
          <%= f.submit "\uF002", class: :search__btn %>
        <% end %>
      </div>
          
      <% if user_signed_in? %>
        <div class="nav__right">
          <div class="nav-btn">
            <%= link_to "投稿する", new_post_path, class: :nav__btn %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          </div>
          <div class="nav-icon">
            <div class="btn-default">
              <div class="btn-bell">
                <%= link_to notifications_path do %>
                  <i class="bi bi-bell size"></i>
                <% end %>
              </div>
              <div class="bottom-right">
                <% if unchecked_notifications.any? %>
                  <i class="bi bi-circle-fill"></i>
                <% end %>
              </div>
            </div>
            <div class="btn-user">
              <%= link_to user_path(current_user) do%>
                <i class="bi bi-person-circle size"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
        </div>
      <% end%>
    </div>
  </div>
</header>