config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create]
  resources :notifications, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many_attached :images
  has_many :post_tags
  has_many :tags, through: :post_tags
  has_many :notifications, dependent: :destroy

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: 'like'
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor(
    :id, :subject, :course, :unit, :introduction, :introduction_time, :development, :development_time, :summary, :summary_time, :teaching_materials,
    :user_id, :created_at, :updated_at, :images,
    :id, :tag_name, :created_at, :updated_at,
    :id, :name, :record_type, :record_id, :blob_id, :created_at
  )

  with_options presence: true do
    validates :subject
    validates :course
    validates :unit
    validates :teaching_materials
  end

  validates :introduction, length: { maximum: 300 }
  validates :development,  length: { maximum: 1000 }
  validates :summary,      length: { maximum: 300 }
  validates :images, length: { maximum: 5, message: 'は5枚以下にしてください' }

  with_options numericality: { only_integer: true, less_than_or_equal_to: 50 } do
    validates :introduction_time
    validates :development_time
    validates :summary_time
  end

  def save
    post = Post.create(subject: subject, course: course, unit: unit, introduction: introduction, introduction_time: introduction_time,
                       development: development, development_time: development_time, summary: summary, summary_time: summary_time, teaching_materials: teaching_materials, images: images, user_id: user_id)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    post = PostTag.create(post_id: post.id, tag_id: tag.id)
  end

  def update(params, post)
    post.post_tags.destroy_all
    tag_name = params.delete(:tag_name)
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?
    tag.save if tag_name.present?
    post.update(params)
    post = PostTag.create(post_id: post.id, tag_id: tag.id) if tag_name.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :move_to_index, except: [:index, :show, :edit]
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @users = User.all
    @posts = Post.all.order('created_at DESC').page(params[:page])
    @posts = @posts.where('unit LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def new
    @post_form = PostForm.new
    @posts = Post.all
  end

  def create
    @post_form = PostForm.new(post_form_params)
    if @post_form.valid?
      @post_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    redirect_to action: :index unless @post.user_id == current_user.id
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
    @post_form.tag_name = @post.tags&.first&.tag_name
  end

  def update
    @post_form = PostForm.new(post_form_params)
    @post_form.images ||= @post.images.blobs
    if @post_form.valid?
      @post_form.update(post_form_params, @post)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private

  def post_form_params
    params.require(:post_form).permit(:subject, :course, :unit, :teaching_materials, :introduction, :introduction_time, :development,
                                      :development_time, :summary, :summary_time, :tag_name, { images: [] }).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% @post.comments.each do |comment| %>
  <div class="comment">
    <li class="comment_list">
      <div class="follow-header">
        <div class="user-image">
          <%= link_to user_path(comment.user_id) do%>
            <% if comment.user.image? %>
              <%= image_tag comment.user.image.url %>
            <% else %>
              <%= image_tag("/images/no-image.png") %>
            <% end %>
          <% end %>
        </div>
        <div class="follow-right">
          <div class="user-nickname">
            <%= comment.user.nickname %>
          </div>
          <div class="user-introduce">
            <%= comment.content %>
          </div>
        </div>
      </div>
    </li>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post_form, url: url, method: method, class: 'registration-main', id: 'new_post', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        投稿
      </h1>
    </div>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">教科名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :subject, class:"input-default", id:"post_subject", placeholder:"例) 社会", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">科目名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :course, class:"input-default", id:"post_course", placeholder:"例)政治経済 ", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">単元名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :unit, class:"input-default", id:"post_unit", placeholder:"例)選挙の仕組み ", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">教材名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :teaching_materials, class:"input-default", id:"post_teaching_materials", placeholder:"例)〇〇出版 ", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">導入時間(数字)</label>
        <span class="indispensable">任意</span>
      </div>
      <span>
      <%= f.text_field :introduction_time, class:"input-name", id:"post_introduction_time", placeholder:"例)5", maxlength:"40" %>分
      </span>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">導入</label>
        <span class="indispensable">任意</span>
      </div>
        <%= f.text_area :introduction, class:"input-class", id:"post_introduction", placeholder:"導入を記入してください", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">展開時間(数字)</label>
        <span class="indispensable">任意</span>
      </div>
      <span>
        <%= f.text_field :development_time, class:"input-name", id:"post_development_time", placeholder:"例)40", maxlength:"40" %>分
      </span>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">展開</label>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_area :development, class:"input-class", id:"post_development", placeholder:"展開を記入してください", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">まとめ時間(数字)</label>
        <span class="indispensable">任意</span>
      </div>
      <span>
        <%= f.text_field :summary_time, class:"input-name", id:"post_summary_time", placeholder:"例)5", maxlength:"40" %>分
      </span>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">まとめ</label>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_area :summary, class:"input-class", id:"post_summary", placeholder:"まとめを記入してください", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">板書案・スライド</label>
        <span class="indispensable">任意</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
        <%= f.file_field :images, name: 'post_form[images][]', data: {index: 0}, id:"post_images" %>
      </div>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">タグ</label>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_field :tag_name, class:"input-default", id:"post_tag_name", placeholder:"例)選挙" %>
      <div id="search-result"></div>
    </div>

    <div class="actions">
      <%= f.submit "投稿する", class: :form__btn %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card__body">
    <div class="card__header">
      <%= link_to user_path(post.user.id) do%>
        <div class="user-image">
          <% if post.user.image? %>
            <%= image_tag post.user.image.url %>
          <% else %>
            <%= image_tag("/images/no-image.png") %>
          <% end %>
        </div>
      <% end %>
      
      <div class="user__name">
        <%= link_to "#{post.user.nickname}先生", user_path(post.user.id) %>
      </div>
      <% if user_signed_in? && current_user.id == post.user_id %>
        <div class="post-edit">
          <%= link_to edit_post_path(current_user.id) do %>
            <i class="bi bi-gear"></i>
          <% end %> 
        </div>
      <% end %>
    </div>

    <div class="card-img">
      <% if post.images.present? %>
        <%= link_to image_tag(post.images[0], class: :card__img ), post_path(post.id) if post.images.attached? %>
      <% else %>
        <%= link_to image_tag('no-post.png', class: :card__img ), post_path(post.id) %>
      <% end %>
    </div>
    
    <div class="card__name">
      <div class=card__title>
        <%= link_to post.course, post_path(post.id), class: :card__title %>
      </div>
      <div class="card_sub_title">
        <%= link_to post.unit, post_path(post.id), class: :card_sub_title %>
      </div>
    </div>
    <div class="card-footer">
      <div class="like-btn">
        <div id="like-btn-<%= post.id %>">
          <%= render 'likes/like', post: post %>
        </div>
      </div>
      <%= link_to post_path(post.id) do %>
      <div class="chat-btn">
        <div class="chat-icon">
          <i class="bi bi-chat-dots"></i>
        </div>
        <div class="chat-count">
          <%= post.comments.count %>
        </div>
      </div>
      <% end%>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% breadcrumb :post_edit, @post %>
<%= render partial: "form", locals:{url: post_path(@post.id), method: :patch} %>

app/views/posts/index.html.erb
<% if params[:page].nil? || params[:page] == 1 %>
  <% breadcrumb :root %>
<% else %>
  <% breadcrumb :posts_pagination, params[:page] %>
<% end %>

<div class='title-contents'>
  <h2 class='service-title'>
    教員の未来を明るくする教YOU
  </h2>
  <p class='service-explain'>
    教員の業務を教YOU（共有）できる！
  </p>
  <p class='service-explain'>
    教YOU（共有）アプリです
  </p>
</div>

<div class='feature-contents'>
  <h2 class='title'>
    教YOUの特徴
  </h2>
  <ul class='feature-lists'>
    <li class='list'>
      <%= image_tag "share.png", class:"list-pict" %>
      <h3 class='feature-list-text'>
        授業を教YOU（共有）
      </h3>
      <p class='feature-list-description'>
        多くの授業を共有することで日々の授業作成に悩む時間が無くなります！また、フィードバックをもらい授業のアップデートに繋がることも！
      </p>
    </li>
    <li class='list'>
      <%= image_tag "connection.png", class:"list-pict" %>
      <h3 class='feature-list-text'>
        教員間のネットワーク
      </h3>
      <p class='feature-list-description'>
        繋がりを作り、教員間の何気ない会話も楽しめます！また、授業以外の悩みや不安を共有することで解決に繋がることも！
      </p>
    </li>
    <li class='list'>
      <%= image_tag "like.png", class:"list-pict" %>
      <h3 class='feature-list-text'>
        いいねで授業を保存
      </h3>
      <p class='feature-list-description'>
        お気に入りの授業はいいねで保存できます！
      </p>
    </li>
  </ul>
</div>

<main class="main">
  <div class="inner">
    <div class="greeting">
      <% if user_signed_in? %>
        <%= "こんにちは" %>
        <%= link_to "#{current_user.nickname}", user_path(current_user), class: :greeting__link %>
        <%= "先生" %>
      <% end%> 
    </div>

    <h2 class="page-heading">
      <%= "みんなの投稿"%>
    </h2>
    <div class="card__wrapper">
      <%= render partial: "post", collection: @posts %>
    </div>
    <div class="paginate">
    <%= paginate @posts %>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<% breadcrumb :new_post %>
<%= render partial: "form", locals: {url: posts_path, method: :post} %>

app/views/posts/show.html.erb
<% breadcrumb :post_show, @post %>
<div class="registration-main">
  <div class="form-wrap">
    <div class="card__header">
      <div class="user-image">
        <% if @post.user.image? %>
          <%= link_to image_tag @post.user.image.url %>
        <% else %>
          <%= image_tag("/images/no-image.png") %>
        <% end %>
      </div>
      <div class="user__name">
        <%= link_to "#{@post.user.nickname}先生", user_path(@post.user.id) %>
      </div>
      <div class="post-icon">
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <div class="gear-icon">
            <%= link_to edit_post_path do %>
              <i class="bi bi-gear"></i>
            <% end %> 
          </div>
          <div class="trush-icon">
            <%= link_to post_path(@post), method: :delete, data: { confirm: "投稿を削除してもよろしいですか？" } do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="post__show__title">
      基本情報
    </div>

    <table class="table__2">
      <tbody>
        <tr>
          <th class="table__col5">教科名</th>
          <td class="table__col6"><%= @post.subject %></td>
        </tr>
        <tr>
          <th class="table__col5">科目名</th>
          <td class="table__col6"><%= @post.course%></td>
        </tr>
        <tr>
          <th class="table__col5">単元名</th>
          <td class="table__col6"><%= @post.unit %></td>
        </tr>
        <tr>
          <th class="table__col5">教材名</th>
          <td class="table__col6"><%= @post.teaching_materials %></td>
        </tr>
        <tr>
          <th class="table__col5">タグ</th>
          <td class="table__col6"><%= @post.tags&.first&.tag_name %></td>
        </tr>
      </tbody>
    </table>

    <div class="post__show__title">
      授業の展開
    </div>

    <table class="table__3">
      <tbody>
        <th class="table__col7">導入(<%= @post.introduction_time %>)分</th>
          <td class="table__col8"><%= @post.introduction %></td>
        </tr>
        <tr>
          <th class="table__col9">展開(<%= @post.development_time %>)分</th>
          <td class="table__col10"><%= @post.development %></td>
        </tr>
        <tr>
          <th class="table__col7">まとめ(<%= @post.summary_time %>)分</th>
          <td class="table__col8"><%= @post.summary %></td>
        </tr>
      </tbody>
    </table>

    <div class="post__show__title">
      板書案・スライド・添付資料
    </div>

    <div class="post_show_image">
      <% if @post.user.image? %>
        <% if @post.images.present? %>
          <div class="post__image">
            <div class="previews">
              <div class="slider">
                <% @post.images[0..-1].each do |image| %>
                  <%= image_tag image %>
                <%end%>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= image_tag("/images/no-post.png") %>
      <% end %>
    </div>

    <div class="post__show__title">
      コメント
    </div>
    <div class="post__comments">
      <div id="comments">
        <div class="h4">＜コメント一覧＞</div>
          <ul class="comments_lists">
            <%= render "comment" %>
          </ul>
        </div>
      </div>
      <div class="comment-form">
        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>
            <div class="field">
              <%= f.text_field :content, id:"comment_content", class:"input-comment", placeholder:"コメントを入力してください"%>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% else %>
            <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %> 
      </div>
    </div>
  </div>
</div>